### GET / route

GET http://localhost:3000
Content-Type: application/json

### GET / route

POST http://localhost:3000/users/login
Content-Type: application/json

### POST new user

POST http://localhost:3000/users/registration
Content-Type: application/json

{"name": "cszc","email":"reszapi@gjggghkjhjgil.com","password":"SauherHentaiKepek67"}

### GET new user

GET  http://localhost:3000/users/getUser/1
Content-Type: application/json


### POST new weather

POST http://localhost:3000/users/registration
Content-Type: application/json

{
  "name": "John Doe",
  "email": "joh@example.com",
  "password": "Abcd1234"
}
